"""empty message

Revision ID: 036b34142c85
Revises: 5043732da193
Create Date: 2016-10-26 00:32:04.154161

"""

# revision identifiers, used by Alembic.
revision = '036b34142c85'
down_revision = '5043732da193'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_centers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('health_centers', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_centers', 'name')
    op.drop_column('health_centers', 'deleted_at')
    ### end Alembic commands ###
