"""empty message

Revision ID: 36bddd7529f4
Revises: 4edbacbed714
Create Date: 2016-12-15 00:45:08.296110

"""

# revision identifiers, used by Alembic.
revision = '36bddd7529f4'
down_revision = '4edbacbed714'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_centers_plans',
    sa.Column('health_center_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_center_id'], ['health_centers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('health_center_id', 'plan_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_centers_plans')
    op.drop_table('plans')
    ### end Alembic commands ###
