"""empty message

Revision ID: 4edbacbed714
Revises: 4573effc5b3a
Create Date: 2016-12-03 17:20:03.436359

"""

# revision identifiers, used by Alembic.
revision = '4edbacbed714'
down_revision = '4573effc5b3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_centers', sa.Column('location', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_centers', 'location')
    ### end Alembic commands ###
