"""empty message

Revision ID: 54966a834c61
Revises: 81d48acfe4fa
Create Date: 2017-03-19 21:49:20.633103

"""

# revision identifiers, used by Alembic.
revision = '54966a834c61'
down_revision = '81d48acfe4fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
