"""empty message

Revision ID: 6ff9dcd79ffc
Revises: 6b39aba1408d
Create Date: 2016-12-18 17:26:25.996330

"""

# revision identifiers, used by Alembic.
revision = '6ff9dcd79ffc'
down_revision = '6b39aba1408d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors_specialities',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'speciality_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors_specialities')
    op.drop_table('specialities')
    ### end Alembic commands ###
