"""empty message

Revision ID: 81d48acfe4fa
Revises: e3d689cb5bd3
Create Date: 2017-03-19 21:29:46.260022

"""

# revision identifiers, used by Alembic.
revision = '81d48acfe4fa'
down_revision = 'e3d689cb5bd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
