"""empty message

Revision ID: 8a6308e6bfa1
Revises: d76c336a877e
Create Date: 2017-02-05 17:34:55.000606

"""

# revision identifiers, used by Alembic.
revision = '8a6308e6bfa1'
down_revision = 'd76c336a877e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
