"""empty message

Revision ID: 97d224da2983
Revises: 4fbab2f3a0ea
Create Date: 2017-02-05 19:36:44.716923

"""

# revision identifiers, used by Alembic.
revision = '97d224da2983'
down_revision = '4fbab2f3a0ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'doctor_id')
    ### end Alembic commands ###
