"""empty message

Revision ID: af52e47f3e01
Revises: 36bddd7529f4
Create Date: 2016-12-18 12:03:56.036532

"""

# revision identifiers, used by Alembic.
revision = 'af52e47f3e01'
down_revision = '36bddd7529f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_centers_plans', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_centers_plans', 'deleted_at')
    ### end Alembic commands ###
