"""empty message

Revision ID: c5fbe706e1bd
Revises: af52e47f3e01
Create Date: 2016-12-18 15:49:18.592889

"""

# revision identifiers, used by Alembic.
revision = 'c5fbe706e1bd'
down_revision = 'af52e47f3e01'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_centers_plans', 'deleted_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_centers_plans', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
