"""empty message

Revision ID: e3d689cb5bd3
Revises: 872fe0371398
Create Date: 2017-03-19 12:38:17.005117

"""

# revision identifiers, used by Alembic.
revision = 'e3d689cb5bd3'
down_revision = '872fe0371398'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'doctors', ['doctor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    ### end Alembic commands ###
